---
version: 2.1

executors:
  packer:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/packer:latest
    resource_class: medium
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-images-mamono210/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  yamllint: orbss/yamllint@0.0.4

jobs:
  packer:
    executor: packer
    parameters:
      ami-name:
        type: string
      ansible-playbook-git-repo:
        type: string
      ansible-playbook-git-repo-version:
        default: 'main'
        type: string
      ssh-username:
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: "cci_pakcer_aws-iam_wp_install_<< parameters.ami-name >>"
          session-duration: '3600'
      - run:
          name: Show Packer version
          command: packer --version
      - run:
          name: Set golden image ami id to environment variables
          command: |
            SOURCE_AMI_ID=$(aws ec2 describe-images \
            --owners $AMI_OWNER_ID \
            --filters "Name=name, Values=<< parameters.ami-name >>*" \
            --query 'Images[*][CreationDate, ImageId, Name]' \
            --output text | sort -r | awk 'NR==1 {print $2}')
            echo "SOURCE_AMI_ID=${SOURCE_AMI_ID}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Retrieve Ansible playbook
          command: |
            git clone "<< parameters.ansible-playbook-git-repo >>" -b "<< parameters.ansible-playbook-git-repo-version >>"
      - run:
          name: Packer build
          command: |
            AMI_NAME="wordpress_golden-image_<< parameters.ami-name >>-`date \"+%s\"`"
            TAG_NAME="wordpress_golden-image_<< parameters.ami-name >> `date --date \"9 hours\" \"+%Y-%m-%d %H:%M:%S UTC+9\"`"

            packer build \
            -var "ami_name=${AMI_NAME}" \
            -var "aws_profile=default" \
            -var "aws_region=ap-northeast-1" \
            -var "source_ami_id=${SOURCE_AMI_ID}" \
            -var "ssh_username=<< parameters.ssh-username >>" \
            -var "tag_name=${TAG_NAME}" \
            build.pkr.hcl
          no_output_timeout: 30m
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace
  yamllint:
    executor: yamllint/default
    steps:
      - checkout
      - yamllint/execute

workflows:
  version: 2.1
  packer:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - packer:
          context: AWS_OPENID_CONNECT_TOKENS
          ami-name: 'centos-stream9'
          ansible-playbook-git-repo: 'https://github.com/ansible-playbooks-mamono210/wordpress_install.git'
          ssh-username: 'ec2-user'
          requires:
            - yamllint
